"""Deterministic, rule-based explanations.

For every returned memory the engine records concrete reasons it matched —
matched speaker, memory type, keywords, confidence threshold, status, date range,
month, meeting, or participant. Each reason carries the weighted score
contribution from the ranking model. Explanations are derived purely from the
filter and the data; nothing is generated by a language model.
"""

from __future__ import annotations

from ..storage import StoredMeeting, StoredMemory
from .models import ExplanationReason, RetrievalExplanation, RetrievalFilter
from .ranking import RankingWeights, ScoreComponents


def _body(memory: StoredMemory, meeting: StoredMeeting | None) -> str:
    parts = [memory.text, memory.speaker or "", *memory.metadata.values()]
    if meeting is not None:
        parts.append(meeting.title or "")
        parts.extend(meeting.participants)
    return " ".join(parts).lower()


def explain_match(
    memory: StoredMemory,
    meeting: StoredMeeting | None,
    applied: RetrievalFilter,
    components: ScoreComponents,
    weights: RankingWeights,
) -> RetrievalExplanation:
    """Build the ordered list of reasons ``memory`` matched ``applied``."""
    reasons: list[ExplanationReason] = []

    for speaker in sorted(applied.speakers):
        if memory.speaker == speaker:
            reasons.append(ExplanationReason("speaker", f"speaker {speaker}"))

    for memory_type in sorted(applied.memory_types):
        if memory.memory_type == memory_type:
            reasons.append(ExplanationReason("type", f"memory type {memory_type}"))

    body = _body(memory, meeting)
    keyword_weight = weights.text * components.text
    for term in applied.terms:
        if term in body:
            reasons.append(ExplanationReason("keyword", f'keyword "{term}"', keyword_weight))

    if applied.phrase_core and applied.phrase_core in memory.text.lower():
        reasons.append(
            ExplanationReason(
                "phrase",
                f'exact phrase "{applied.phrase_core}"',
                weights.phrase * components.phrase,
            )
        )

    if applied.min_confidence is not None:
        reasons.append(
            ExplanationReason(
                "confidence",
                f"confidence \u2265 {applied.min_confidence:.2f}",
                weights.confidence * components.confidence,
            )
        )

    for status in sorted(applied.statuses, key=lambda member: member.value):
        if memory.status == status:
            reasons.append(
                ExplanationReason(
                    "status", f"status {status.value}", weights.status * components.status
                )
            )

    if (applied.date_from or applied.date_to) and meeting is not None and meeting.date:
        low = applied.date_from or "..."
        high = applied.date_to or "..."
        reasons.append(
            ExplanationReason(
                "date", f"within date range {low}..{high}", weights.recency * components.recency
            )
        )

    if applied.months and meeting is not None and meeting.date:
        month = int(meeting.date[5:7])
        if month in applied.months:
            reasons.append(
                ExplanationReason(
                    "date", f"meeting month {month:02d}", weights.recency * components.recency
                )
            )

    if applied.meeting_ids and memory.meeting_id in applied.meeting_ids:
        reasons.append(
            ExplanationReason(
                "meeting", f"meeting {memory.meeting_id}", weights.meeting * components.meeting
            )
        )

    if applied.participants and meeting is not None:
        present = set(meeting.participants)
        for participant in sorted(applied.participants):
            if participant in present:
                reasons.append(
                    ExplanationReason(
                        "participant",
                        f"participant {participant}",
                        weights.meeting * components.meeting,
                    )
                )

    if not reasons:
        reasons.append(
            ExplanationReason(
                "confidence",
                f"confidence {memory.confidence:.2f}",
                weights.confidence * components.confidence,
            )
        )

    return RetrievalExplanation(tuple(reasons))
